# handle-team-basics
This notebook combines two datasets (mens_basketball_programs and mens_institutions) into a single dataframe to be used in the future.

In [16]:
# necessary imports
import pandas as pd

In [17]:
# mens institutions
institutions = pd.read_csv('../data/csv/mens_institutions.csv')
institutions = institutions.sort_values('School')

# mens programs
programs = pd.read_csv('../data/csv/mens_basketball_programs.csv')
programs = programs.sort_values('School').reset_index(drop=True)

In [18]:
programs["Tournament appearances"] = programs["Tournament appearances"].str.extract(r'(\d+)').astype(int)
programs["Final Four appearances"] = programs["Final Four appearances"].str.extract(r'(\d+)').astype(int)
programs["Championship wins"] = programs["Championship wins"].str.extract(r'(\d+)').astype(int)

In [19]:
programs['School'] = programs['School'].replace(to_replace='\(.*\)', value='', regex=True).str.strip()
print(programs['School'].to_list())

['Abilene Christian University', 'Alabama Agricultural and Mechanical University', 'Alabama State University', 'Alcorn State University', 'American University', 'Appalachian State University', 'Arizona State University', 'Arkansas State University', 'Auburn University', 'Austin Peay State University', 'Ball State University', 'Baylor University', 'Bellarmine University', 'Belmont University', 'Bethune–Cookman University', 'Boise State University', 'Boston College', 'Boston University', 'Bowling Green State University', 'Bradley University', 'Brigham Young University', 'Brown University', 'Bryant University', 'Bucknell University', 'Butler University', 'California Baptist University', 'California Polytechnic State University', 'California State University, Bakersfield', 'California State University, Fresno', 'California State University, Fullerton', 'California State University, Long Beach', 'California State University, Northridge', 'California State University, Sacramento', 'Campbell University', 'Canisius University', 'Central Connecticut State University', 'Central Michigan University', 'Charleston Southern University', 'Chicago State University', 'Clemson University', 'Cleveland State University', 'Coastal Carolina University', 'Colgate University', 'College of Charleston', 'College of the Holy Cross', 'Colorado State University', 'Columbia University in the City of New York', 'Coppin State University', 'Cornell University', 'Creighton University', 'Dartmouth College', 'Davidson College', 'DePaul University', 'Delaware State University', 'Drake University', 'Drexel University', 'Duke University', 'Duquesne University of the Holy Spirit', 'East Carolina University', 'East Tennessee State University', 'Eastern Illinois University', 'Eastern Kentucky University', 'Eastern Michigan University', 'Eastern Washington University', 'Elon University', 'Fairfield University', 'Fairleigh Dickinson University', 'Florida Agricultural and Mechanical University', 'Florida Atlantic University', 'Florida Gulf Coast University', 'Florida International University', 'Florida State University', 'Fordham University', 'Furman University', 'Gardner–Webb University', 'George Mason University', 'Georgetown University', 'Georgia Institute of Technology', 'Georgia Southern University', 'Georgia State University', 'Gonzaga University', 'Grambling State University', 'Grand Canyon University', 'Hampton University', 'Harvard University', 'High Point University', 'Hofstra University', 'Houston Christian University', 'Howard University', 'Idaho State University', 'Illinois State University', 'Indiana State University', 'Indiana University Bloomington', 'Indiana University–Purdue University Indianapolis', 'Iona University', 'Iowa State University of Science and Technology', 'Jackson State University', 'Jacksonville State University', 'Jacksonville University', 'James Madison University', 'Kansas State University', 'Kennesaw State University', 'Kent State University', 'La Salle University', 'Lafayette College', 'Lamar University', 'Le Moyne College', 'Lehigh University', 'Liberty University', 'Lindenwood University', 'Lipscomb University', 'Long Island University', 'Longwood University', 'Louisiana State University and Agricultural and Mechanical College', 'Louisiana Tech University', 'Loyola Marymount University', 'Loyola University Chicago', 'Loyola University Maryland', 'Manhattan College', 'Marist College', 'Marquette University', 'Marshall University', 'McNeese State University', 'Mercer University', 'Merrimack College', 'Miami University', 'Michigan State University', 'Middle Tennessee State University', 'Mississippi State University for Agriculture and Applied Science', 'Mississippi Valley State University', 'Missouri State University', 'Monmouth University', 'Montana State University', 'Morehead State University', 'Morgan State University', "Mount Saint Mary's University", 'Murray State University', 'New Jersey Institute of Technology', 'New Mexico State University', 'Niagara University', 'Nicholls State University', 'Norfolk State University', 'North Carolina Agricultural and Technical State University', 'North Carolina Central University', 'North Carolina State University', 'North Dakota State University of Agriculture and Applied Sciences', 'Northeastern University', 'Northern Arizona University', 'Northern Illinois University', 'Northern Kentucky University', 'Northwestern State University of Louisiana', 'Northwestern University', 'Oakland University', 'Oklahoma State University–Stillwater', 'Old Dominion University', 'Oral Roberts University', 'Oregon State University', 'Pepperdine University', 'Portland State University', 'Prairie View A&M University', 'Presbyterian College', 'Princeton University', 'Providence College', 'Purdue University', 'Purdue University Fort Wayne', 'Queens University of Charlotte', 'Quinnipiac University', 'Radford University', 'Rider University', 'Robert Morris University', 'Rutgers University–New Brunswick', 'Sacred Heart University', 'Saint Bonaventure University', 'Saint Francis University', "Saint John's University", "Saint Joseph's University", 'Saint Louis University', "Saint Mary's College of California", "Saint Peter's University", 'Sam Houston State University', 'Samford University', 'San Diego State University', 'San Jose State University', 'Santa Clara University', 'Seattle University', 'Seton Hall University', 'Siena College', 'South Carolina State University', 'South Dakota State University', 'Southeast Missouri State University', 'Southeastern Louisiana University', 'Southern Illinois University Carbondale', 'Southern Illinois University Edwardsville', 'Southern Methodist University', 'Southern University and A&M College', 'Southern Utah University', 'Stanford University', 'State University of Iowa', 'State University of New York at Albany', 'State University of New York at Binghamton', 'State University of New York at Buffalo', 'State University of New York at Stony Brook', 'Stephen F. Austin State University', 'Stetson University', 'Stonehill College', 'Syracuse University', 'Tarleton State University', 'Temple University', 'Tennessee State University', 'Tennessee Technological University', 'Texas A&M University', 'Texas A&M University–Commerce', 'Texas A&M University–Corpus Christi', 'Texas Christian University', 'Texas Southern University', 'Texas State University', 'Texas Tech University', 'The Citadel, The Military College of South Carolina', 'The College of William and Mary in Virginia', 'The George Washington University', 'The Ohio State University', 'The Ohio University', 'The Pennsylvania State University', 'The University of Akron', 'The University of Alabama', 'The University of Mississippi', 'The University of New Mexico', 'The University of Tennessee at Chattanooga', 'The University of Tennessee at Martin', 'The University of Tennessee, Knoxville', 'The University of Texas Rio Grande Valley', 'The University of Texas at Arlington', 'The University of Texas at Austin', 'The University of Texas at El Paso', 'The University of Texas at San Antonio', 'The University of Tulsa', 'The University of Vermont and State Agricultural College', 'Towson University', 'Troy University', 'Tulane University of Louisiana', 'United States Air Force Academy', 'United States Military Academy', 'United States Naval Academy', 'University of Alabama at Birmingham', 'University of Arizona', 'University of Arkansas', 'University of Arkansas at Little Rock', 'University of Arkansas at Pine Bluff', 'University of California, Berkeley', 'University of California, Davis', 'University of California, Irvine', 'University of California, Los Angeles', 'University of California, Riverside', 'University of California, San Diego', 'University of California, Santa Barbara', 'University of Central Arkansas', 'University of Central Florida', 'University of Cincinnati', 'University of Colorado Boulder', 'University of Connecticut', 'University of Dayton', 'University of Delaware', 'University of Denver', 'University of Detroit Mercy', 'University of Evansville', 'University of Florida', 'University of Georgia', 'University of Hawaiʻi at Mānoa', 'University of Houston', 'University of Idaho', 'University of Illinois Chicago', 'University of Illinois Urbana-Champaign', 'University of Kansas', 'University of Kentucky', 'University of Louisiana at Lafayette', 'University of Louisiana at Monroe', 'University of Louisville', 'University of Maine', 'University of Maryland Eastern Shore', 'University of Maryland, Baltimore County', 'University of Maryland, College Park', 'University of Massachusetts Amherst', 'University of Massachusetts Lowell', 'University of Memphis', 'University of Miami', 'University of Michigan', 'University of Minnesota', 'University of Missouri–Columbia', 'University of Missouri–Kansas City', 'University of Montana', 'University of Nebraska Omaha', 'University of Nebraska–Lincoln', 'University of Nevada, Las Vegas', 'University of Nevada, Reno', 'University of New Hampshire', 'University of New Orleans', 'University of North Alabama', 'University of North Carolina at Asheville', 'University of North Carolina at Chapel Hill', 'University of North Carolina at Charlotte', 'University of North Carolina at Greensboro', 'University of North Carolina at Wilmington', 'University of North Dakota', 'University of North Florida', 'University of North Texas', 'University of Northern Colorado', 'University of Northern Iowa', 'University of Notre Dame du Lac', 'University of Oklahoma', 'University of Oregon', 'University of Pennsylvania', 'University of Pittsburgh', 'University of Portland', 'University of Rhode Island', 'University of Richmond', 'University of San Diego', 'University of San Francisco', 'University of South Alabama', 'University of South Carolina', 'University of South Carolina Upstate', 'University of South Dakota', 'University of South Florida', 'University of Southern California', 'University of Southern Indiana', 'University of Southern Mississippi', 'University of St. Thomas', 'University of Toledo', 'University of Utah', 'University of Virginia', 'University of Washington', 'University of Wisconsin–Green Bay', 'University of Wisconsin–Madison', 'University of Wisconsin–Milwaukee', 'University of Wyoming', 'University of the Incarnate Word', 'University of the Pacific', 'Utah State University', 'Utah Tech University', 'Utah Valley University', 'Valparaiso University', 'Vanderbilt University', 'Villanova University', 'Virginia Commonwealth University', 'Virginia Military Institute', 'Virginia Polytechnic Institute and State University', 'Wagner College', 'Wake Forest University', 'Washington State University', 'Weber State University', 'West Virginia University', 'Western Carolina University', 'Western Illinois University', 'Western Kentucky University', 'Western Michigan University', 'Wichita State University', 'William Marsh Rice University', 'Winthrop University', 'Wofford College', 'Wright State University', 'Xavier University', 'Yale University', 'Youngstown State University']

<>:1: SyntaxWarning: invalid escape sequence '\('
<>:1: SyntaxWarning: invalid escape sequence '\('
/var/folders/0z/fbvp30yd2rqglt77ftznhyp80000gn/T/ipykernel_86680/2569291075.py:1: SyntaxWarning: invalid escape sequence '\('
  programs['School'] = programs['School'].replace(to_replace='\(.*\)', value='', regex=True).str.strip()

In [20]:
merged = pd.merge(programs, institutions, on='School', how='outer', suffixes=('_df1', '_df2'))
remove_columns = ["Nickname_df2", "Home arena"]
merged.drop(columns=remove_columns, inplace=True)
merged.rename(columns={'Nickname_df1': 'Nickname'}, inplace=True)
merged['ID'] = range(1, len(merged) + 1)
ordered_columns = ["ID", "School", "Common Name", "Nickname", "City", "State", "Type", "Subdivision", "Primary Conference", "Tournament appearances", "Final Four appearances", "Championship wins"]
merged = merged[ordered_columns]

merged

,ID,School,Common Name,Nickname,City,State,Type,Subdivision,Primary Conference,Tournament appearances,Final Four appearances,Championship wins
0,1,Abilene Christian University,Abilene Christian,Wildcats,Abilene,TX,Private,FCS,Western Athletic Conference,2,0,0
1,2,Alabama Agricultural and Mechanical University,Alabama A&M,Bulldogs,Normal,AL,Public,FCS,Southwestern Athletic Conference,1,0,0
2,3,Alabama State University,Alabama State,Hornets,Montgomery,AL,Public,FCS,Southwestern Athletic Conference,4,0,0
3,4,Alcorn State University,Alcorn State,Braves,Lorman,MS,Public,FCS,Southwestern Athletic Conference,6,0,0
4,5,American University,American,Eagles,Washington,DC,Private,Non-football,Patriot League,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
357,358,Wofford College,Wofford,Terriers,Spartanburg,SC,Private,FCS,Southern Conference,5,0,0
358,359,Wright State University,Wright State,Raiders,Dayton,OH,Public,Non-football,Horizon League,4,0,0
359,360,Xavier University,Xavier,Musketeers,Cincinnati,OH,Private,Non-football,Big East Conference,29,0,0
360,361,Yale University,Yale,Bulldogs,New Haven,CT,Private,FCS,Ivy League,6,0,0
361,362,Youngstown State University,Youngstown State,Penguins,Youngstown,OH,Public,FCS,Horizon League,0,0,0

In [21]:
merged.to_csv('../data/dataframes/team_info.csv', index=False)